### ISSUE TITLE
Cannot run kraken issuses

### ISSUE THREAD

**Issue by Fredericwu** [redhat-chaos/krkn#171] opened 2021-11-01 08:28 UTC
I tried to run kraken according to the following link:  https://github.com/cloud-bulldozer/kraken/blob/master/docs/installation.md, But the following error message appeared:
**Git**
root@node5:~/kraken# python3 run_kraken.py -c config/config.yaml
2021-10-31 18:15:33,077 [INFO] Starting kraken
2021-10-31 18:15:33,111 [INFO] Initializing client to talk to the Kubernetes cluster
2021-10-31 18:15:33,744 [INFO] Publishing kraken status at http://0.0.0.0:8081
2021-10-31 18:15:33,746 [INFO] Starting http server at http://0.0.0.0:8081

2021-10-31 18:15:33,751 [INFO] Fetching cluster info
error: the server doesn't have a resource type "clusterversion"
2021-10-31 18:15:35,183 [ERROR] Failed to run kubectl get clusterversion, error: Command 'kubectl get clusterversion' returned non-zero exit status 1.
root@node5:~/kraken# 

**Run containerized version**
root@node5:~/kraken/containers# docker run --name=kraken --net=host -v /root/.kube/config:/root/.kube/config:Z -v /root/kraken/config/config.yaml:/root/kraken/config/config.yaml:Z -v /root/kraken/scenarios:/root/kraken/scenarios:Z -d quay.io/openshift-scale/kraken:latest 
5495c5c3fb22f17d3a8259115d776bb2045f45bc3f9c8105d6ec1940b9567b7b
root@node5:~/kraken/containers# 
root@node5:~/kraken/containers# 
root@node5:~/kraken/containers# docker logs -f kraken
2021-11-01 07:51:16,194 [INFO] Starting kraken
2021-11-01 07:51:16,233 [INFO] Initializing client to talk to the Kubernetes cluster
2021-11-01 07:51:39,675 [INFO] Publishing kraken status at http://0.0.0.0:8440
2021-11-01 07:51:39,679 [INFO] Starting http server at http://0.0.0.0:8440

2021-11-01 07:51:39,680 [INFO] Fetching cluster info
error: the server doesn't have a resource type "clusterversion"
2021-11-01 07:51:44,257 [ERROR] Failed to run kubectl get clusterversion, error: Command 'kubectl get clusterversion' returned non-zero exit status 1.

**kubernetes info:**
root@node5:~/kraken/containers# kubectl get node
NAME        STATUS   ROLES                  AGE    VERSION
k8smaster   Ready    control-plane,master   199d   v1.20.5
k8snode1    Ready    <none>                 199d   v1.20.5
node3       Ready    control-plane,master   199d   v1.20.5
node4       Ready    <none>                 196d   v1.20.5
node5       Ready    control-plane,master   176d   v1.20.5

I don’t know the reason for the failure,Can someone explain it
If you need more information,please let me know.
Thx

**Comment by Fredericwu** [comment] 2021-11-04 01:34
I checked the source code. Many of them use OpenShift commands. Is it suitable for k8s clusters?

**Comment by chaitanyaenr** [comment] 2021-11-24 18:00
Hi @Fredericwu, thanks for reporting the issue. You are right, there are a couple of references to oc cli which we are planning to replace with kubectl. We have been testing/running Kraken on OpenShift at the moment but the plan is to definitely improve the coverage to make sure the scenarios work on Kubernetes environments as well. We are tracking it in the following issues: https://github.com/cloud-bulldozer/kraken/issues/185, https://github.com/cloud-bulldozer/kraken/issues/186. We will keep you posted. Thanks.

**Comment by sandrobonazzola** [comment] 2022-09-05 09:38
@chaitanyaenr is this still an issue?

**Comment by chaitanyaenr** [comment] 2022-09-06 12:49
@sandrobonazzola the failure reported in the issue is fixed by https://github.com/redhat-chaos/krkn/pull/256 but there are still a few references of oc calls that would need to replaced which are tracked in other issues, so closing this issue. @Fredericwu please feel free to reopen in case of any issues. Thanks.

**Closed by chaitanyaenr** 2022-09-06 12:49 UTC
